### ISSUE TITLE
Docstring for `context.config` does not match mypy

### ISSUE THREAD

**Issue by nbhargava** [sqlalchemy/alembic#904] opened 2021-09-07 16:47 UTC
**Describe the bug**

Within `config.py`, the following is present in a docstring:
> Within an ``env.py`` script, this is available
> via the :attr:`.EnvironmentContext.config` attribute,
> which in turn is available at ``alembic.context``::
>
>     from alembic import context
>     some_param = context.config.get_main_option("my option")

but `context.config` yields a mypy error. The new stubs in `context.pyi` seem to overwrite local stubs, meaning that it's unclear how to work around this.

**Expected behavior**

`context.config` should be recognized as valid in mypy. Or, the docstring should be updated.

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example, with the migration script and/or the SQLAlchemy tables or models involved.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website.

Run mypy on version 1.7.1 over the following file:

```py
from alembic import context

context.config
```

**Error**

```
foo.py:3: error: Module has no attribute "config"; maybe "configure"?  [attr-defined]
```

**Versions.**
 - OS: macOS 10.15.7
 - Python: 3.8.8
 - Alembic: 1.7.1
 - SQLAlchemy: 1.4.23
 - Database: N/A
 - DBAPI: N/A

**Additional context**

N/A

**Have a nice day!**

**Comment by CaselIT** [comment] 2021-09-07 19:18
Hi,

This is a duplicate of https://github.com/sqlalchemy/alembic/issues/900

**Closed by CaselIT** 2021-09-07 19:18 UTC
Labels: requires triage
