### ISSUE TITLE
[Question]Can i use async db driver to serve db changes?

### ISSUE THREAD

**Issue by crotaoryx** [sqlalchemy/alembic#805] opened 2021-02-26 15:47 UTC
Hi guys!
I'm newbie with alembic and wanted clarify one thing.

As i understood based on docs, alembic uses sync database driver(for example, psycopg2) to serve db changes. At the same time i saw SQLAlchemy is moving forward with async, which means i can use asyncpg. As result, it seems app need has both of them - psycopg2 and asyncpg. 

Is it possible to use just asyncpg for alembic and SQLAlchemy? Or maybe it's planned future feature? I know that alembic don't need async features to modify db, but i think it's good for "clean requirements" purpose use one driver for both cases.
Or i'm wrong  and maybe missing something?

Thanks!

**Comment by CaselIT** [comment] 2021-02-26 15:57
Hi,

You are right, currently alembic does not support async drivers.
As far as I know this is not currently planned, since there are not many advantages of async in alembic use case, other than avoiding to deal with two different db driver.

That being saint I think we would accept PR that add that functionality.
Thinking at how sqlalchemy async is implemented, it may just be that an async version of env is required? @zzzeek

**Comment by crotaoryx** [comment] 2021-02-26 16:20
Thanks for answer @CaselIT!
Hope there is someone interested with this implementation and skills to prepare PR.

Have a great day!

**Comment by CaselIT** [comment] 2021-02-26 18:12
Speaking with mike on gitter it is indeed just the env.py that needs to change, to something like this:

```py

await def run_migrations_online():
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    engine = create_async_engine(...)

    def do_migrations(connection):
        context.configure(connection=connection, target_metadata=target_metadata, **config_options)

        with context.begin_transaction():
            context.run_migrations()

    async with engine.connect() as connection:
        await connection.run_sync(do_migrations)


if context.is_offline_mode():
    run_migrations_offline()
else:
    import asyncio
    asyncio.run(run_migrations_online())
```

**Comment by crotaoryx** [comment] 2021-02-26 18:22
Great! Thank you @CaselIT, I'll try this!
I hope there is no difference to use uvloop instead of asyncio.

**Comment by CaselIT** [comment] 2021-02-26 18:35
There shouldn't, but I don't think it would make a difference in this case using one or the other

**Comment by sqla-tester** [comment] 2021-02-26 20:24
**CaselIT** has proposed a fix for this issue in the **master** branch:

**Add async template to Alembic** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2609

**Comment by zzzeek** [comment] 2021-02-27 00:42
you konw you could just leave everything as it is, and use a database URL with "?async_fallback=True".    this will run each DBAPI method in a new asyncio loop under the hood.  @CaselIT would that be a less trouble?

**Comment by CaselIT** [comment] 2021-02-27 08:11
Ah right we also support that. One thing I'm not sure is if we want to make that api public. IIRC it is currently not documented.

Also maybe having the async call in env feels less magic for people?

**Closed** 2021-02-27 17:05 UTC
Labels: asyncio, documentation, migration environment, use case

**Comment by zzzeek** [comment] 2021-02-27 17:06
well theyre both magic :)   but this way the user feels like they're a little bit more a part of it :)

**Comment by crotaoryx** [comment] 2021-02-27 19:29
HI @zzzeek! 
Do you mean all i need is just change
_postgresql+asyncpg://root:root@db_host:5432/db_name_
to 
_postgresql+asyncpg://root:root@db_host:5432/db_name?async_fallback=True_ 
?
> you konw you could just leave everything as it is, and use a database URL with "?async_fallback=True". this will run each DBAPI method in a new asyncio loop under the hood. @CaselIT would that be a less trouble?

**Comment by CaselIT** [comment] 2021-02-27 19:34
No that's not needed if you modify the env with the async bits.
Adding `async_fallback` would make the normal sync env work, but it's probably a bit too "magic" for most people :)

**Comment by zzzeek** [comment] 2021-02-27 21:36
@crotaoryx yes, you can just change the URL to have ?async_fallback=True and you have to change nothing else.   What this basically does is move the "sync->async" part to happen for each database call, rather than your initial asyncio.run().

@CaselIT and I tend to differ on this approach, for me "magic is magic" but he is correct that the more longhand way is a *tiny* bit less "magic".  It's also more efficient at scale though that doesn't matter much for a migration script.

**Comment by janaSunrise** [comment] 2021-03-12 11:38
Hi there! I am also trying to use it with my sqlalchemy project which uses asyncpg, but I also got the normal `env.py`.

The version is `1.5.7`, which is the latest.
Should I configure the version / code, or follow some other steps?

**Comment by CaselIT** [comment] 2021-03-12 12:16
both should work. we added a faq entry for this https://alembic.sqlalchemy.org/en/latest/cookbook.html#using-asyncio-with-alembic

please let us know if you find issues

**Comment by janaSunrise** [comment] 2021-03-12 12:23
![Screenshot from 2021-03-12 17-51-04](https://user-images.githubusercontent.com/56873669/110939693-d1336100-835b-11eb-81dd-40628554a6fc.png)
Just got this issue

**Comment by CaselIT** [comment] 2021-03-12 12:47
I cannot reproduce, are you sure you are using an updated version of alembic?

**Comment by janaSunrise** [comment] 2021-03-12 12:49
Yeah, I am using the latest of `1.5.7`

**Comment by CaselIT** [comment] 2021-03-12 13:40
I guess you should try uninstalling and re-installing it. I tried in an empty docker image, so installing from a clean environment works

**Comment by janaSunrise** [comment] 2021-03-13 06:02
Alright, I'll do that. I am having the trouble with pipenv locking and I even commented on their official repo's issues too. Its just too crappy atm

**Comment by gruianichita** [comment] 2021-07-21 16:20
> Speaking with mike on gitter it is indeed just the env.py that needs to change, to something like this:
> 
> ```python
> async def run_migrations_online():
>     """Run migrations in 'online' mode.
> 
>     In this scenario we need to create an Engine
>     and associate a connection with the context.
> 
>     """
>     engine = create_async_engine(...)
> 
>     def do_migrations(connection):
>         context.configure(connection=connection, target_metadata=target_metadata, **config_options)
> 
>         with context.begin_transaction():
>             context.run_migrations()
> 
>     async with engine.connect() as connection:
>         await connection.run_sync(do_migrations)
> 
> 
> if context.is_offline_mode():
>     run_migrations_offline()
> else:
>     import asyncio
>     asyncio.run(run_migrations_online())
> ```

I have used this one, but I have this error
```sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1030, "Got error 168 - 'Unknown (generic) error from engine' from storage engine")
[SQL: 
CREATE TABLE alembic_version (
        version_num VARCHAR(32) NOT NULL, 
        CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
)

]
(Background on this error at: https://sqlalche.me/e/14/2j85)
Exception ignored in: <function Connection.__del__ at 0x1038479d0>
Traceback (most recent call last):
  File "/Users/nichitagruia/.local/share/virtualenvs/ProductsFinding-YAX73Aiq/lib/python3.9/site-packages/aiomysql/connection.py", line 1072, in __del__
  File "/Users/nichitagruia/.local/share/virtualenvs/ProductsFinding-YAX73Aiq/lib/python3.9/site-packages/aiomysql/connection.py", line 298, in close
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 700, in close
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 746, in call_soon
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
(ProductsFinding) (base) nichitagruia@MacBook-Pro-Nichita ProductsFinding % 
```

**Comment by CaselIT** [comment] 2021-07-21 16:58
we just added (yesterday) a clarification regarding that error at https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html#synopsis-core

rldr: add an `await enginge.dispose()` before the end of the `run_migrations_online` function. This is not needed, since the connection will be closed in any case since python is exiting, but it's better than to have the exception :)

**Comment by gruianichita** [comment] 2021-07-21 19:50
doesn't work for me(( 

db.py
```python
import sqlalchemy
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker

from settings.base import SQLALCHEMY_DATABASE_URI

engine = create_async_engine(url=SQLALCHEMY_DATABASE_URI, future=True, echo=True)
# Base = declarative_base()
Session = sessionmaker(engine, expire_on_commit=False, class_=AsyncSession)
metadata = sqlalchemy.MetaData()


async def get_sql_db():
    async with Session() as session:
        yield session

```

env.py

```python
async def run_migrations_online():
    def do_migrations(connection):
        context.configure(connection=connection, target_metadata=target_metadata)

        with context.begin_transaction():
            context.run_migrations()

    async with engine.connect() as connection:
        await connection.run_sync(do_migrations)

    await engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    import asyncio

    asyncio.run(run_migrations_online())
```

I just try to create the first migration but I got the same problem :(
```
alembic revision --autogenerate -m "Added user table"
```

**Comment by CaselIT** [comment] 2021-07-21 20:23
I just tried and I cannot reproduce.
You may want to try using the NullPool when using alembic that should solve the issue since it disables connection pooling

**Comment by gruianichita** [comment] 2021-07-21 20:44
@CaselIT 
my proj looks like https://github.com/gruianichita/alembic-err
crash after this command 
```
alembic revision --autogenerate -m "Added user table"
```

**Comment by CaselIT** [comment] 2021-07-23 21:09
I cannot reproduce on windows and of linux (fedora). Commenting `await engine.dispose()` reproduces the error

If you have a reproducer it's probably best to report in another issue

**Comment by CaselIT** [comment] 2021-10-14 12:17
There's also a cookbook entry: https://alembic.sqlalchemy.org/en/latest/cookbook.html#using-asyncio-with-alembic

**Comment by WittyGeek797** [comment] 2022-02-03 08:00
Alembic has added async support for the `env.py` file and can be used with the below command:
`alembic init -t async <script_directory_here>`
Worked like a charm for me.

**Comment by alejoar** [comment] 2022-02-14 14:09
What about upgrading programmatically? 

When running `await alembic.command.upgrade(config, "head")` in my code I get 
```
uvicorn/lifespan/on.py:89: RuntimeWarning: coroutine 'run_migrations_online' was never awaited
  return
```

**Comment by alejoar** [comment] 2022-02-14 16:38
@zzzeek I can't get it to work.

Following your instructions and running the upgrade in my code I get all the sql upgrade comments printed to the terminal and it finishes with:

```
INFO  [sqlalchemy.engine.Engine] [no key 0.00015s] ()
INFO  [sqlalchemy.engine.Engine] INSERT INTO alembic_version (version_num) VALUES ('49f3009ed437') RETURNING alembic_version.version_num
INFO  [sqlalchemy.engine.Engine] [generated in 0.00033s] ()
INFO  [sqlalchemy.engine.Engine] ROLLBACK
```

Nothing happens in the DB. I'm not sure what's going on.

**Comment by CaselIT** [comment] 2022-02-14 23:10
Hi @alejoar 

Could you open a new issue or discussion with a complete example?
It's a bit difficult to otherwise suggest solutions without the full picture.

Thanks

**Comment by alejoar** [comment] 2022-02-15 09:56
@CaselIT thank you. I created a minimal example repo and started a discussion here: https://github.com/sqlalchemy/alembic/discussions/991

**Comment by rednaxelakvas** [comment] 2023-10-12 01:38
> **CaselIT** has proposed a fix for this issue in the **master** branch:
> 
> **Add async template to Alembic** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2609

this was extremely helpfull! ty

**Comment by coding-billi** [comment] 2024-07-13 12:10
THANK YO SOO MUCH EVERYONE I FINALLY WITH THE HELP OF THE ASYNC env.py TEMPLATE SOLVED MY PROBLEM ITS BEEN TWO DAYS!!! my stackoverflow question: https://stackoverflow.com/questions/78742213/alembic-not-recognizing-multiple-models-using-fastapi
