### ISSUE TITLE
create_type=False on postgres enum is not propagated with `--autogenerate`

### ISSUE THREAD

**Issue by olirice** [sqlalchemy/alembic#796] opened 2021-02-19 23:11 UTC
**Describe the bug**
When generating a migration using `--autogenerate` that includes a `sqlalchemy.dialects.postgresql.ENUM`, the `create_type=False` argument is not propagated into the rendered definition.

For example:
```python
some_enum = ENUM(
    "a", "b", "c", name="abc", schema="public", create_type=False
)
```

Renders as
```
postgresql.ENUM('a', 'b', 'c', name='abc', schema='public')
```

**Expected behavior**
Renders as
```
postgresql.ENUM('a', 'b', 'c', name='abc', schema='public', create_type=False)
```

**To Reproduce**
Here is a test to reproduce
```py
from sqlalchemy import MetaData
from sqlalchemy.dialects.postgresql import ENUM

from alembic import autogenerate
from alembic.autogenerate import api
from alembic.migration import MigrationContext
from alembic.testing import eq_ignore_whitespace
from alembic.testing.fixtures import TestBase


class PostgresqlRenderTest(TestBase):

    """test individual directives"""

    def setUp(self):
        context = MigrationContext.configure(
            dialect_name="postgresql"
        )
        self.autogen_context = api.AutogenContext(context)

    def test_render_enum_with_create_type_false(self):
        some_enum = ENUM(
            "a", "b", "c", name="abc", schema="public", create_type=False
        )

        eq_ignore_whitespace(
            autogenerate.render._repr_type(some_enum, self.autogen_context),
            """
        postgresql.ENUM(
            'a', 'b', 'c',
            name='abc',
            schema='public',
            create_type=False
        )
        """,
        )
```

**Error**
```
AssertionError: 
    "postgresql.ENUM('a', 'b', 'c', name='abc', schema='public')"
    != " postgresql.ENUM( 'a', 'b', 'c', name='abc', schema='public', create_type=False ) "
```

**Versions.**
 - OS:  macOS 10.15.4
 - Python: 3.7.2
 - Alembic: 1.5.4
 - SQLAlchemy: 1.3.*
 - Database: Postgresql

**Comment by zzzeek** [comment] 2021-02-20 01:08
it's very likely this is already reported as we are collecting all the ENUM issues for a hopeful "single pass" to get the whole thng at once.

**Comment by zzzeek** [comment] 2021-02-20 01:09
here we are, dupe of #735 .   ENUMs are basically unimplemented within autogenerate right now until we can get a resource to work on this issue.

**Closed by zzzeek** 2021-02-20 01:09 UTC
Labels: autogenerate for enums
