### ISSUE TITLE
False change for unique constraint with case-sensitive names in 1.4.0

### ISSUE THREAD

**Issue by ods** [sqlalchemy/alembic#654] opened 2020-02-06 09:57 UTC
PostgreSQL, a unique constraint with uppercase letters in name. `_compare_indexes_and_uniques` takes name as `_constraint_sig.name` (just the name without quotes) for constraint from connection, but as `_constraint_sig.md_name_to_sql_name(context)` (gives the name in double quotes) for constraint from metadata. That causes false changes detection with script that drops and creates the same constraint.

The following change solves the problem:
```
--- a/alembic/autogenerate/compare.py
+++ b/alembic/autogenerate/compare.py
@@ -541,7 +541,7 @@ def _compare_indexes_and_uniques(
     conn_uniques_by_name = dict((c.name, c) for c in conn_unique_constraints)
     conn_indexes_by_name = dict((c.name, c) for c in conn_indexes)
     conn_names = dict(
-        (c.name, c)
+        (c.md_name_to_sql_name(autogen_context), c)
         for c in conn_unique_constraints.union(conn_indexes)
         if c.name is not None
     )
```

**Comment by zzzeek** [comment] 2020-02-06 15:31
Ok there's no test case for that so need to add one.

**Comment by zzzeek** [comment] 2020-02-06 15:37
I can't reproduce.  Can you provide a reproduction case?  I think just a CREATE TABLE that is generating the false positives should be enough clue.

```
    def test_nothing_changed_uq_w_mixed_case_name(self):
        m1 = MetaData()
        m2 = MetaData()

        Table(
            "nothing_changed",
            m1,
            Column("id", Integer, primary_key=True),
            Column("x", Integer),
            UniqueConstraint("x", name="SomeConstraint"),
            mysql_engine="InnoDB",
        )

        Table(
            "nothing_changed",
            m2,
            Column("id", Integer, primary_key=True),
            Column("x", Integer),
            UniqueConstraint("x", name="SomeConstraint"),
            mysql_engine="InnoDB",
        )
        diffs = self._fixture(m1, m2)
        eq_(diffs, [])

```

in PG the table is created as:

```
CREATE TABLE nothing_changed (
	id SERIAL NOT NULL, 
	x INTEGER, 
	PRIMARY KEY (id), 
	CONSTRAINT "SomeConstraint" UNIQUE (x)
)

```

**Comment by sqla-tester** [comment] 2020-02-06 15:39
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Handle mixed case identifiers correctly.** https://gerrit.sqlalchemy.org/1709

**Comment by zzzeek** [comment] 2020-02-06 15:39
that's just my test, will run it against multiple PG versions to confirm no issue so far.

**Comment by zzzeek** [comment] 2020-02-06 15:59
oh, well duh, the whole issue that was fixed with that logic didn't happen in master :)   k we're good thanks

**Comment by zzzeek** [comment] 2020-02-06 16:17
different fix though.   names aren't supposed to be quoted here.

**Closed** 2020-02-06 19:00 UTC
Labels: autogenerate - detection, bug, postgresql, regression
