### ISSUE TITLE
Update table with new enum field

### ISSUE THREAD

**Issue by hesmebye** [sqlalchemy/alembic#1053] opened 2022-06-07 11:37 UTC
**Describe the bug**
When updating table with a new Enum data type, alembic does not create the new Enum data type before it is referenced from the update table request.  This seems to work fine when creating a new table.

**Expected behavior**
Create Enum type first, then add the table column which reference it.

**To Reproduce**
Create table in db with alembic.  Update table by adding a Enum colum.

```py
from sqlalchemy.ext.declarative import declarative_base
meta = MetaData(
    naming_convention={
        "ix": "ix_%(column_0_label)s",
        "uq": "uq_%(table_name)s_%(column_0_name)s",
        "ck": "ck_%(table_name)s_%(constraint_name)s",
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
        "pk": "pk_%(table_name)s",
    }
)
Base = declarative_base(metadata=meta)

# Enum python type
class FileContentType(str, enum.Enum):
    GENERAL_FILE = "GENERAL_FILE"
    DATA_FILE = "DATA_FILE"
    LAYER_FILE = "LAYER_FILE"

# sqlalchemy data type -  simplified version
class File(Base):
    __tablename__ = "file"
    file_id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("uuid_generate_v4()"),
    )
    
    file_content_type = Column(
        sqltypes.Enum(schemas.FileContentType),
        server_default=schemas.FileContentType.GENERAL_FILE,
        nullable=True,
    )

```

**Error**

```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade d6a2b6fd5b35 -> a7bb2874b83c, Add support for multiple files. 
Traceback (most recent call last):
  File "/home/helge/.cache/pypoetry/virtualenvs/fm-data-api-qtwaf0_d-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/helge/.cache/pypoetry/virtualenvs/fm-data-api-qtwaf0_d-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedObject: type "filecontenttype" does not exist
LINE 1: ALTER TABLE file ADD COLUMN file_content_type filecontenttyp...
                                                      ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/helge/.cache/pypoetry/virtualenvs/fm-data-api-qtwaf0_d-py3.10/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/home/helge/.cache/pypoetry/virtualenvs/fm-data-api-qtwaf0_d-py3.10/lib/python3.10/site-packages/alembic/config.py", line 588, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/helge/.cache/pypoetry/virtualenvs/fm-data-api-qtwaf0_d-py3.10/lib/python3.10/site-packages/alembic/config.py", line 582, in main
    self.run_cmd(cfg, options)
  File "/home/helge/.cache/pypoetry/virtualenvs/fm-data-api-qtwaf0_d-py3.10/lib/python3.10/site-packages/alembic/config.py", line 559, in run_cmd
    fn(
  File "/home/helge/.cache/pypoetry/virtualenvs/fm-data-api-qtwaf0_d-py3.10/lib/python3.10/site-packages/alembic/command.py", line 320, in upgrade
    script.run_env()
  File "/home/helge/.cache/pypoetry/virtualenvs/fm-data-api-qtwaf0_d-py3.10/lib/python3.10/site-packages/alembic/script/base.py", line 563, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/helge/.cache/pypoetry/virtualenvs/fm-data-api-qtwaf0_d-py3.10/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/helge/.cache/pypoetry/virtualenvs/fm-data-api-qtwaf0_d-py3.10/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Utvikling/devops/field-manager/field-manager-data-api/alembic/env.py", line 107, in <module>
    run_migrations_online()
  File "/mnt/c/Utvikling/devops/field-manager/field-manager-data-api/alembic/env.py", line 101, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/helge/.cache/pypoetry/virtualenvs/fm-data-api-qtwaf0_d-py3.10/lib/python3.10/site-packages/alembic/runtime/environment.py", line 851, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/helge/.cache/pypoetry/virtualenvs/fm-data-api-qtwaf0_d-py3.10/lib/python3.10/site-packages/alembic/runtime/migration.py", line 620, in run_migrations
    step.migration_fn(**kw)
  File "/mnt/c/Utvikling/devops/field-manager/field-manager-data-api/alembic/versions/a7bb2874b83c_add_support_for_multiple_files.py", line 29, in upgrade
    op.add_column('file', sa.Column('file_content_type', sa.Enum('GENERAL_FILE', 'DATA_FILE', 'LAYER_FILE', name='filecontenttype'), server_default='GENERAL_FILE', nullable=True))
  File "<string>", line 8, in add_column
  File "<string>", line 3, in add_column
  File "/home/helge/.cache/pypoetry/virtualenvs/fm-data-api-qtwaf0_d-py3.10/lib/python3.10/site-packages/alembic/operations/ops.py", line 2047, in add_column
    return operations.invoke(op)
  File "/home/helge/.cache/pypoetry/virtualenvs/fm-data-api-qtwaf0_d-py3.10/lib/python3.10/site-packages/alembic/operations/base.py", line 392, in invoke
    return fn(self, operation)
  File "/home/helge/.cache/pypoetry/virtualenvs/fm-data-api-qtwaf0_d-py3.10/lib/python3.10/site-packages/alembic/operations/toimpl.py", line 154, in add_column
    operations.impl.add_column(table_name, column, schema=schema, **kw)
  File "/home/helge/.cache/pypoetry/virtualenvs/fm-data-api-qtwaf0_d-py3.10/lib/python3.10/site-packages/alembic/ddl/impl.py", line 320, in add_column
    self._exec(base.AddColumn(table_name, column, schema=schema))
  File "/home/helge/.cache/pypoetry/virtualenvs/fm-data-api-qtwaf0_d-py3.10/lib/python3.10/site-packages/alembic/ddl/impl.py", line 193, in _exec
    return conn.execute(construct, multiparams)
  File "/home/helge/.cache/pypoetry/virtualenvs/fm-data-api-qtwaf0_d-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1306, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/helge/.cache/pypoetry/virtualenvs/fm-data-api-qtwaf0_d-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File "/home/helge/.cache/pypoetry/virtualenvs/fm-data-api-qtwaf0_d-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1398, in _execute_ddl
    ret = self._execute_context(
  File "/home/helge/.cache/pypoetry/virtualenvs/fm-data-api-qtwaf0_d-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/helge/.cache/pypoetry/virtualenvs/fm-data-api-qtwaf0_d-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/helge/.cache/pypoetry/virtualenvs/fm-data-api-qtwaf0_d-py3.10/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/helge/.cache/pypoetry/virtualenvs/fm-data-api-qtwaf0_d-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/helge/.cache/pypoetry/virtualenvs/fm-data-api-qtwaf0_d-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedObject) type "filecontenttype" does not exist
LINE 1: ALTER TABLE file ADD COLUMN file_content_type filecontenttyp...
```

**Versions.**
 - OS: Ubuntu 20.04
 - Python: 3.10
 - Alembic: 1.7.7
 - SQLAlchemy: 1.4.26
 - Database: Postgresql 11.15
 - DBAPI: psycopg2-binary = "^2.9.1"

**Additional context**
Workaround by adding directly into the version scripts

**Comment by zzzeek** [comment] 2022-06-07 12:55
dupe of #278.   apply the type creation manually for now.

**Closed by zzzeek** 2022-06-07 12:55 UTC
Labels: duplicate, autogenerate for enums
