### ISSUE TITLE
Mypy complains about config attribute

### ISSUE THREAD

**Issue by donkirkby** [sqlalchemy/alembic#900] opened 2021-09-06 17:11 UTC
**Describe the bug**
Mypy generates this error on the `env.py` script:

> Module has no attribute "config"; maybe "configure"?

**Expected behavior**
No error message on `env.py` script generated by the `alembic init` command.

**To Reproduce**
```
$ alembic init alembic
  Creating directory /project/alembic ...  done
  Creating directory /project/alembic/versions ...  done
  Generating /project/alembic.ini ...  done
  Generating /project/alembic/env.py ...  done
  Generating /project/alembic/script.py.mako ...  done
  Generating /project/alembic/README ...  done
  Please edit configuration/connection/logging settings in '/project/alembic.ini' before proceeding.
$ mypy .
alembic/env.py:10: error: Module has no attribute "config"; maybe "configure"?
Found 1 error in 1 file (checked 1 source file)
$ 
```

**Error**

```
alembic/env.py:10: error: Module has no attribute "config"; maybe "configure"?
```

**Versions.**
 - OS: Ubuntu 20.04
 - Python: 3.8.10
 - Alembic: 1.7.0 (also 1.7.1)
 - SQLAlchemy: 1.4.23
 - Database: None
 - DBAPI: ?
 - mypy: 0.910

**Additional context**
I worked around the problem by telling mypy not to check the config attribute on line 10 of `env.py`.

```python
config = context.config  # type: ignore
```

It's just a guess, but I wondered if [this type hint] is confusing Mypy.

```python
config: "Config" = None  # type:ignore[assignment]
```

[this type hint]: https://github.com/sqlalchemy/alembic/blob/rel_1_7_1/alembic/runtime/environment.py#L94

**Have a nice day!**
Thanks for sharing the project, and thanks for adding type hints.

**Comment by CaselIT** [comment] 2021-09-06 18:49
That's for the report.

I think the issue is in the generated pyi file. IIRC it's filtered out

**Comment by sqla-tester** [comment] 2021-09-06 21:22
**CaselIT** has proposed a fix for this issue in the **master** branch:

**Added missing attributes from context stubs.** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/3066

**Closed** 2021-09-15 20:54 UTC
Labels: bug, pep 484
