### ISSUE TITLE
1.5.0 Doesn't have the templates directory

### ISSUE THREAD

**Issue by alonbentamar** [sqlalchemy/alembic#781] opened 2021-01-19 15:11 UTC
**Describe the bug**
The `templates` directory in the alembic installation does not exist, which raises errors on initializations and `list_templates`

**Expected behavior**
Alembic should be installed with the default templates (`multidb`, `pylons`, `generic`) and the alembic commands should work out of the box.

**To Reproduce**
Install `alembic` 1.5.0 in a clean env, and run either `alembic init .` or `alembic list_templates`.
The following output is for the `list_templates` command:

```
❯ alembic list_templates
```

**Error**

```
Available templates:

Traceback (most recent call last):
  File "/Volumes/code/src/my_project/.venv/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/Volumes/code/src/my_project/.venv/lib/python3.9/site-packages/alembic/config.py", line 559, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/Volumes/code/src/my_project/.venv/lib/python3.9/site-packages/alembic/config.py", line 553, in main
    self.run_cmd(cfg, options)
  File "/Volumes/code/src/my_project/.venv/lib/python3.9/site-packages/alembic/config.py", line 530, in run_cmd
    fn(
  File "/Volumes/code/src/my_project/.venv/lib/python3.9/site-packages/alembic/command.py", line 17, in list_templates
    for tempname in os.listdir(config.get_template_directory()):
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/code/src/my_project/.venv/lib/python3.9/site-packages/alembic/templates'
```

**Versions.**
 - OS: macOS 11.1
 - Python: 3.9
 - Alembic: 1.5.0
 - SQLAlchemy: 1.3.22
 - Database: PostgresDB
 - DBAPI: not sure

**Have a nice day!**

**Comment by zzzeek** [comment] 2021-01-19 15:24
dupe of #780 Alembic 1.5.1 is now released

**Closed by zzzeek** 2021-01-19 15:24 UTC
Labels: bug, duplicate
