### ISSUE TITLE
add a timestamp token that can be part of the file_template

### ISSUE THREAD

**Issue by thibautfrain** [sqlalchemy/alembic#622] opened 2019-11-12 10:50 UTC
Wouldn't it be nice to have the migration files (the ones which are in the `migration/versions` folder) sorted by creation date. These are hard to retrieve without the help of the command `alembic history`.

I propose a new variable to use in the `file_template` option, that could be placed at first, so that the file order could be maintained.

Is that reasonable and isn't that somehow a shallow request ?

**Comment by zzzeek** [comment] 2019-11-12 14:13
Sure can you:

a. propose the format of this date stamp

b. provide a pull request with tests

**Comment by thibautfrain** [comment] 2019-11-18 10:50
My idea at first, was to provide an incremental value so that we could have migration files organized as follow :
    migrations/
        version/
            0_initial_migration.py
            1_alter_column_x_on_table_y.py
            2_change_type_of_column_z_on_table_w

As previously mentioned, it is perhaps a shallow feature to implement, comparing what has to be done in terms of development  (thinking about getting the value from history or directly from fs) and the usefulness of the feature.

The other interpretation, that was raised in your answer, was to provide a timestamp value, and so I see 2 kinds of values:
    - A true timestamp, which should be the result of `int(datetime.timestamp(create_date)`
    - A datetime value in the form of `datetime.strftime(create_date, "%Y%m%d%H%M%S")` but could be easily obtain without new development with the existing datetime based variables.

To conclude, I have no idea which one is preferable.

**Comment by zzzeek** [comment] 2019-11-18 15:21
the incremental value is a non-starter.  this is one of the disastrous decisions made by the SQLAlchemy-migrate project that Alembic sought to correct for.    Database migrations are not necessarily linear and there is always a need to add new migrations between existing ones when dealing with situations like branch merges.

As for the date tokens, we actually already have these and this issue is a duplicate of #59 .

it's documented in the [tutorial](https://alembic.sqlalchemy.org/en/latest/tutorial.html?highlight=file_template#editing-the-ini-file):

```
- file_template - this is the naming scheme used to generate new migration files. The value present is the default, so is commented out. Tokens available include:

        %%(rev)s - revision id

        %%(slug)s - a truncated string derived from the revision message

        %%(year)d, %%(month).2d, %%(day).2d, %%(hour).2d, %%(minute).2d, %%(second).2d - components of the create date, by default datetime.datetime.now() unless the timezone configuration option is also used.

- timezone - an optional timezone name (e.g. UTC, EST5EDT, etc.) that will be applied to the timestamp which renders inside the migration file’s comment as well as within the filename. If timezone is specified, the create date object is no longer derived from datetime.datetime.now() and is instead generated as:

datetime.datetime.utcnow().replace(
      tzinfo=dateutil.tz.tzutc()
).astimezone(
    dateutil.tz.gettz(<timezone>)
)



```

**Comment by zzzeek** [comment] 2019-11-18 15:22
this behavior is already documented, so closing.

**Closed by zzzeek** 2019-11-18 15:22 UTC
Labels: duplicate
