### ISSUE TITLE
Stub generator for proxy classes does not generate overload stubs

### ISSUE THREAD

**Issue by vfazio** [sqlalchemy/alembic#1147] opened 2022-12-29 19:22 UTC
**Describe the bug**

The stub generator for proxy classes (`tools/write_pyi.py`) does not generate overload stubs

**Expected behavior**

To accurately reflect the typing of the proxied classes, the overloads should be stubbed out.

**Comment by CaselIT** [comment] 2022-12-30 10:56
Hi,

this seems a duplicate of https://github.com/sqlalchemy/alembic/issues/1146. We can continue to the other one

**Closed by CaselIT** 2022-12-30 10:56 UTC
Labels: bug, pep 484
