### ISSUE TITLE
Server default not matching for `func.now()` with SQLite

### ISSUE THREAD

**Issue by tdaff** [sqlalchemy/alembic#634] opened 2019-12-10 12:57 UTC
My model has 
```python
    created = Column(DateTime, server_default=func.now())
```
And every time I invoke `autogenerate` with `compare_server_default=True` on sqlite, it generates the same migrations that do nothing:

```python
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.alter_column('created',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.alter_column('created',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=True)

    # ### end Alembic commands ###
```

**Comment by zzzeek** [comment] 2019-12-10 14:10
hi -

what Alembic and SQLAlchemy versions please ?

**Comment by zzzeek** [comment] 2019-12-10 14:12
also please try going into your model and setting up the column as:

    created = Column(DateTime, server_default=text('(CURRENT_TIMESTAMP)'))

please do not consider this as a solution proposal, this is only to see if this resolves the problem as a means to identify its source

**Comment by zzzeek** [comment] 2019-12-10 14:21
this issue is not reproducible with current Alembic / SQLAlchemy versions and the issue you describe seems to match what was fixed in #579, so ensure you are on the latest 1.3.1 release.

**Comment by tdaff** [comment] 2019-12-10 15:18
Very strange. Alembic was not even installed into that virtual environment until yesterday and I can see in my terminal session that alembic-1.3.1 sqlalchemy-1.3.11 were installed yesterday afternoon before I started using them.

I have, however, just updated pytest (along with more-itertools, zipp, importlib-metadata, pluggy, py, pyparsing, packaging, pytest, pytest-flask) and the issue has gone away. I don't see how any of those would alter the way that alembic works, but it looks like it's working as intended now.

Apologies for the non-issue and thanks for the quick response.

PS I had tried `server_default=text('(CURRENT_TIMESTAMP)')` and it did not resolve the problem.

**Comment by zzzeek** [comment] 2019-12-10 17:59
What I always do is, use the python interpreter that I'm dealing with, I type "import alembic" and then "alembic.__file__" so I can see exactly where it's coming from.  the venv you have obviously was getting an old alembic from somewhere.   glad I dont have to fix this issue again :)

**Closed by zzzeek** 2019-12-10 17:59 UTC
Labels: question

**Comment by CristianoYL** [comment] 2020-03-07 02:19
Hi, I met the same issue recently after an update. Not sure if it exists prior to the update, but here's what I have:

table definition:
```
...
__tablename__ = 'conditions'

created_at = db.Column(db.DateTime(timezone=True), server_default=db.func.now())
...
```

alembic auto-generated upgrade script:
```
op.create_table('conditions',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    ...
```

error message when rolling out the upgrade:
> sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "(": syntax error
[SQL: 
CREATE TABLE conditions (
	created_at DATETIME DEFAULT now(), 
	last_modified DATETIME DEFAULT now(), 
	id INTEGER NOT NULL, 
	description VARCHAR(255) NOT NULL, 
	CONSTRAINT pk_conditions PRIMARY KEY (id)
)
>
>]

The upgrade works fine with Postgres but I got the above error with SQLite. It looks like the script generated for SQLite has syntax error. I looked at a few other issue threads and tried to manually execute the script in SQLite with `DEFAULT now()` replaced by `DEFAULT (datetime('now', 'localtime'))` and the SQL script would work.

I'm wondering if this is intended, or is there anything wrong?

Thanks in advance!

**Comment by zzzeek** [comment] 2020-03-07 03:24
the func. constructs generate as text("...") that is hardcoded to the target database which you autogenerated against.   so you are probably autogenerating against Postgresql.  To have it run on SQLite you should edit your migration script to use func.now() directly so that it renders SQLite's "CURRENT_TIMESTAMP" when run on that backend.

**Comment by CristianoYL** [comment] 2020-03-11 00:09
> the func. constructs generate as text("...") that is hardcoded to the target database which you autogenerated against. so you are probably autogenerating against Postgresql. To have it run on SQLite you should edit your migration script to use func.now() directly so that it renders SQLite's "CURRENT_TIMESTAMP" when run on that backend.

It works! Thanks! I'm wondering why it isn't the default behavior to generate a generic migration script rather than a dialect-specific one?

**Comment by zzzeek** [comment] 2020-03-11 02:41
because that is much more difficult to implement such that it works in all cases.    for simple func.xyz() maybe not so bad but for any SQL expression more complicated with that we have to reverse-engineer printing out complete Python SQLAlchemy expressions.  if your server default was for example "server_default=func.my_special_proc(func.status() +12) + 18", we would have to read in that whole SQLAlchemy expression and build out a whole new Python compilation system for it that spits out valid Python / SQLAlchemy code.

**Comment by CristianoYL** [comment] 2020-03-11 16:45
That makes a lot of sense. Thanks!
