### ISSUE TITLE
Migrations generation worked in 1.10.3. Now, in 1.10.4, it creates migrations that seem overly complex and migrating them fails

### ISSUE THREAD

**Issue by blockjon-dd** [sqlalchemy/alembic#1288] opened 2023-08-03 05:01 UTC
I have a model to which I added a string column called `color`. In version 1.10.3, I get a reasonable migrations file that is auto generated which roughly looks like this:
```
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spinnaker_pipelines_started', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spinnaker_pipelines_started', 'color')
    # ### end Alembic commands ###
```
however, when I upgrade to 1.10.4, and then I try generating migrations, I get a huge amount of output that have lines that start with:
```
Detected removed unique constraint...
Detect removed index
Detected changed index
....
```

the resulting migrations file has lots of commands that dont work which dont relate to the fact I added a "color" string column.... 

```
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('deployable_commits_sha_key', 'deployable_commits', type_='unique')
    op.drop_index('deployable_commits_sha_key', table_name='deployable_commits')
    op.drop_index('repo_branch', table_name='deployable_commits')
    op.create_index('repo_branch', 'deployable_commits', ['repo', 'branch'], unique=False)
    op.add_column('spinnaker_pipelines_started', sa.Column('color', sa.String(), nullable=True))
        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spinnaker_pipelines_started', 'color')
    op.create_index('repo_branch', 'deployable_commits', [sa.text('repo NULLS FIRST'), sa.text('branch NULLS FIRST')], unique=False)
    op.create_index('deployable_commits_sha_key', 'deployable_commits', [sa.text('sha NULLS FIRST')], unique=False)
    op.create_unique_constraint('deployable_commits_sha_key', 'deployable_commits', ['sha'])
    # ### end Alembic commands ###
```

Looking for guidance as to what I might need to do differently.

If it helps, I'm using cockroachdb, which is based on postgres.

Also, when I tried to execute the large migration that as auto generated, I got this error:

```
sqlalchemy.exc.OperationalError: (psycopg2.errors.ObjectNotInPrerequisiteState) index "repo_branch" being dropped, try again later
```

```
sqlalchemy-cockroachdb==2.0.1
SQLAlchemy==2.0.19
```

**Comment by zzzeek** [comment] 2023-08-03 13:52
hi - 

alembic 1.10.4 adds support for detecting additional elements of PG indexes such as ASC or NULLS FIRST.  it would appear that your indexes have these constructs in your PG database but not in your model metadata, *or* you might be using `postgresql_ops` - see #1285.

at the moment., without a reproducer, we can't take any action on this issue without a sample of what the CREATE TABLE /CREATE INDEX looks like for one of these indexes combined with a sample model that reproduces the issue.

**Comment by cedric-roussel** [comment] 2023-08-08 15:38
Hi, I'm not sure this is exactly related but might help.

We have updated to alembic `1.10.4` and we see some changes are always detected and not expected, everytime we generate a new migration.

-- requirements.txt
```
alembic==1.10.4
SQLAlchemy==1.3.18
```

-- models.py
```python
from datetime import datetime

from sqlalchemy import UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, DeclarativeBase

class Base(DeclarativeBase):
    pass

class Exemple(Base):
    __tablename__ = "dummy"
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    a: Mapped[int]
    b: Mapped[int]
    tomb_date: Mapped[datetime] = mapped_column(nullable=True)
    __table_args__ = (
        UniqueConstraint(
            "a",
            "b",
            "tomb_date",
            postgresql_nulls_not_distinct=True,
            name="dummy_a_b_tomb_date_key"
        ),
    )

```

Initial migration is looking great, and postgresql nulls not distinct works.
But when I rerun autogenerate it always detect the same change.

```bash
alembic revision --autogenerate -m "test"
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.ddl.postgresql] Detected sequence named 'dummy_id_seq' as owned by integer column 'dummy(id)', assuming SERIAL and omitting
INFO  [alembic.autogenerate.compare] Detected changed unique constraint 'dummy_a_b_tomb_date_key' on 'dummy': expression ('UNIQUE_CONSTRAINT', 'a', 'b', 'tomb_date') to ('UNIQUE_CONSTRAINT', 'a', 'b', 'tomb_date', ('nulls_not_distinct', True))
  Generating ... /alembic/versions/733f639ec673_test.py ...  done
```

It generates a new migration file every time with the same content
```python
"""test

Revision ID: 733f639ec673
Revises: a96502e5e7d3
Create Date: 2023-08-08 17:29:31.612196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '733f639ec673'
down_revision: Union[str, None] = 'a96502e5e7d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dummy_a_b_tomb_date_key', 'dummy', type_='unique')
    op.create_unique_constraint('dummy_a_b_tomb_date_key', 'dummy', ['a', 'b', 'tomb_date'], postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dummy_a_b_tomb_date_key', 'dummy', type_='unique')
    op.create_unique_constraint('dummy_a_b_tomb_date_key', 'dummy', ['a', 'b', 'tomb_date'])
    # ### end Alembic commands ###

```

**Comment by CaselIT** [comment] 2023-08-08 15:58
sqlalchemy 1.3 (or v2) has no support for postgresql_nulls_not_distinct, and it will not them in them when creating the constraint.

It's actually strange that it does not raise for unknown dialect option

**Comment by cedric-roussel** [comment] 2023-08-08 16:10
I'm on latest, sqlachemy 2.0.19

**Comment by CaselIT** [comment] 2023-08-08 16:21
ok, this seems a different issue, let's open a new issue

**Comment by CaselIT** [comment] 2023-08-31 19:56
closing since there was no reply.

**Closed by CaselIT** 2023-08-31 19:56 UTC
Labels: bug, autogenerate - detection, postgresql, awaiting info
