### ISSUE TITLE
Self-referential composite foreign key results in crash

### ISSUE THREAD

**Issue by otonnesen** [sqlalchemy/alembic#1226] opened 2023-04-24 00:22 UTC
**Describe the bug**
Adding a self-referencing composite foreign key constraint to an existing table results in a crash, both when attempting to autogenerate a migration or when running a hand-written migration.

**Expected behavior**
Expected no crash.

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example, with the migration script and/or the SQLAlchemy tables or models involved.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website.

```py
# repro.py
from sqlalchemy import (
    Boolean,
    Column,
    ForeignKeyConstraint,
    Integer,
    MetaData,
    Table,
    UniqueConstraint,
)

metadata_obj = MetaData()

my_table = Table(
    "my_table",
    metadata_obj,
    Column("id", Integer),
    Column("parent_id", Integer),
    Column("some_flag", Boolean),
    UniqueConstraint("id", "some_flag"),
    # ForeignKeyConstraint(
    #     ["parent_id", "some_flag"], ["my_table.id", "my_table.some_flag"]
    # ),
)
```

Running `autogenerate` using the above file produces the following migration script, as expected:

```py
# alembic/versions/c23d15b7881e_.py
"""empty message

Revision ID: c23d15b7881e
Revises:
Create Date: 2023-04-23 17:01:32.974153

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c23d15b7881e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "my_table",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("some_flag", sa.Boolean(), nullable=True),
        sa.UniqueConstraint("id", "some_flag"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("my_table")
    # ### end Alembic commands ###
```

If we now uncomment the ForeignKeyConstraint in repro.py:

```py
# repro.py
...
my_table = Table(
    ...
    ForeignKeyConstraint(
        ["parent_id", "some_flag"], ["my_table.id", "my_table.some_flag"]
    ),
)
```

Then `upgrade` and `autogenerate` again, we get the following error:

**Error**

```
(venv) [user@hostname /alembic-bug]$ alembic revision --autogenerate
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.autogenerate.compare] Detected added foreign key (parent_id, some_flag)(id, some_flag) on table my_table
Traceback (most recent call last):
  File "/alembic-bug/venv/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/config.py", line 591, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/config.py", line 585, in main
    self.run_cmd(cfg, options)
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/config.py", line 562, in run_cmd
    fn(
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/command.py", line 229, in revision
    script_directory.run_env()
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/script/base.py", line 576, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/alembic-bug/alembic/env.py", line 80, in <module>
    run_migrations_online()
  File "/alembic-bug/alembic/env.py", line 74, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/runtime/environment.py", line 868, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/runtime/migration.py", line 609, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/command.py", line 205, in retrieve_migrations
    revision_context.run_autogenerate(rev, context)
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/autogenerate/api.py", line 525, in run_autogenerate
    self._run_environment(rev, migration_context, True)
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/autogenerate/api.py", line 572, in _run_environment
    compare._populate_migration_script(
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/autogenerate/compare.py", line 58, in _populate_migration_script
    upgrade_ops.reverse_into(downgrade_ops)
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/operations/ops.py", line 2478, in reverse_into
    reversed([op.reverse() for op in self.ops])
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/operations/ops.py", line 2478, in <listcomp>
    reversed([op.reverse() for op in self.ops])
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/operations/ops.py", line 2453, in reverse
    ops=list(reversed([op.reverse() for op in self.ops])),
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/operations/ops.py", line 2453, in <listcomp>
    ops=list(reversed([op.reverse() for op in self.ops])),
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/operations/ops.py", line 120, in reverse
    return DropConstraintOp.from_constraint(self.to_constraint())
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/operations/ops.py", line 578, in to_constraint
    return schema_obj.foreign_key_constraint(
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/operations/schemaobj.py", line 89, in foreign_key_constraint
    t1 = sa_schema.Table(
  File "<string>", line 2, in __new__
  File "/alembic-bug/venv/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 283, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/alembic-bug/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 435, in __new__
    return cls._new(*args, **kw)
  File "/alembic-bug/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 489, in _new
    with util.safe_reraise():
  File "/alembic-bug/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/alembic-bug/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 485, in _new
    table.__init__(name, metadata, *args, _no_init=False, **kw)
  File "/alembic-bug/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 877, in __init__
    self._init_items(
  File "/alembic-bug/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 230, in _init_items
    spwd(self, **kw)
  File "/alembic-bug/venv/lib/python3.10/site-packages/sqlalchemy/sql/base.py", line 1328, in _set_parent_with_dispatch
    self._set_parent(parent, **kw)
  File "/alembic-bug/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 2341, in _set_parent
    raise exc.DuplicateColumnError(
sqlalchemy.exc.DuplicateColumnError: A column with name 'some_flag' is already present in table 'my_table'.
```

Attempting to write the migration manually results in a similar error when running `upgrade`:

```py
# alembic/versions/01752b138428_.py
"""empty message

Revision ID: 01752b138428
Revises: c23d15b7881e
Create Date: 2023-04-23 17:09:10.841363

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "01752b138428"
down_revision = "c23d15b7881e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_foreign_key(
        op.f("fk_my_table_parentid"),
        "asset",
        "asset",
        ["parentid", "some_flag"],
        ["id", "some_flag"],
    )


def downgrade() -> None:
    pass
```
**Error**

```
(venv) [user@hostname /alembic-bug]$ alembic upgrade +1
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade c23d15b7881e -> 01752b138428, empty message
Traceback (most recent call last):
  File "/alembic-bug/venv/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/config.py", line 591, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/config.py", line 585, in main
    self.run_cmd(cfg, options)
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/config.py", line 562, in run_cmd
    fn(
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/command.py", line 378, in upgrade
    script.run_env()
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/script/base.py", line 576, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/alembic-bug/alembic/env.py", line 80, in <module>
    run_migrations_online()
  File "/alembic-bug/alembic/env.py", line 74, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/runtime/environment.py", line 868, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/runtime/migration.py", line 622, in run_migrations
    step.migration_fn(**kw)
  File "/alembic-bug/alembic/versions/01752b138428_.py", line 20, in upgrade
    op.create_foreign_key(
  File "<string>", line 8, in create_foreign_key
  File "<string>", line 3, in create_foreign_key
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/operations/ops.py", line 665, in create_foreign_key
    return operations.invoke(op)
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/operations/base.py", line 401, in invoke
    return fn(self, operation)
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/operations/toimpl.py", line 176, in create_constraint
    operation.to_constraint(operations.migration_context)
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/operations/ops.py", line 578, in to_constraint
    return schema_obj.foreign_key_constraint(
  File "/alembic-bug/venv/lib/python3.10/site-packages/alembic/operations/schemaobj.py", line 89, in foreign_key_constraint
    t1 = sa_schema.Table(
  File "<string>", line 2, in __new__
  File "/alembic-bug/venv/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 283, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/alembic-bug/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 435, in __new__
    return cls._new(*args, **kw)
  File "/alembic-bug/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 489, in _new
    with util.safe_reraise():
  File "/alembic-bug/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/alembic-bug/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 485, in _new
    table.__init__(name, metadata, *args, _no_init=False, **kw)
  File "/alembic-bug/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 877, in __init__
    self._init_items(
  File "/alembic-bug/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 230, in _init_items
    spwd(self, **kw)
  File "/alembic-bug/venv/lib/python3.10/site-packages/sqlalchemy/sql/base.py", line 1328, in _set_parent_with_dispatch
    self._set_parent(parent, **kw)
  File "/alembic-bug/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 2341, in _set_parent
    raise exc.DuplicateColumnError(
sqlalchemy.exc.DuplicateColumnError: A column with name 'some_flag' is already present in table 'asset'.
```

**Versions.**
 - OS: Debian 11
 - Python: CPython 3.10.10
 - Alembic: alembic==1.10.3
 - SQLAlchemy: SQLAlchemy==2.0.10
 - Database: Postgres 14.4
 - DBAPI: psycopg2==2.9.6

**Additional context**
This crash only seems to occur when altering an existing table; autogenerating an initial migration without the foreign key constraint commented out works as expected.

**Have a nice day!**

**Comment by CaselIT** [comment] 2023-04-24 06:30
Hi

This is a duplicate of https://github.com/sqlalchemy/alembic/issues/1215

**Closed by CaselIT** 2023-04-24 06:30 UTC
Labels: requires triage

**Comment by zzzeek** [comment] 2023-04-24 15:06
my bad, i havent released alembic, i thought everything was out.  will do that now
